### ISSUE TITLE
Optional table definition

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-insert#10]
It would be good if you could define the table columns in the metadata itself, such that the table is created to that specification if it's missing and then records are inserted into that table.

**Comment by simonw** [comment]
Possible syntax:
```yaml
databases:
  data:
    plugins:
      datasette-insert-api:
        tables:
          dogs:
            columns:
              id: int
              name: str
              age: str
              created: _now_datetime_utc
            pk: id
```
Note that the `created` column here uses a magic parameter definition from https://datasette.readthedocs.io/en/stable/sql_queries.html#magic-parameters - there's a plugin hook for those already so other plugins could expand the available options.

The fact that this configuration is nested inside the plugins definition for a named database is a little odd - maybe it would be better to keep everything in a single `datasette-insert-api` block in the root `plugins` key?

**Comment by simonw** [comment]
I can also have a key that controls if random new tables can be created:
```
databases:
  plugins:
    datasette-insert-api:
      databases:
        mydb:
          allow_table_creation: false
```
